/**
 * Represents a document in the knowledge base.
 * 
 * This structure is used to store text content along with its vector embeddings for efficient
 * similarity-based search. Each document is uniquely identified by an `id` and includes a 
 * timestamp indicating when it was created.
 */
export interface Document {
    /**
     * A unique identifier for the document.
     * 
     * This ID is typically auto-generated by the database and is used for efficient retrieval
     * and management of documents.
     */
    id: string;

    /**
     * The textual content of the document.
     * 
     * This content is what users provide as knowledge, and it can come from various sources
     * like plain text, web pages, or PDF files.
     */
    content: string;

    /**
     * The vector embedding representation of the document's content.
     * 
     * These embeddings are typically generated using models like OpenAI's `text-embedding-ada-002`
     * or HuggingFace's `all-MiniLM-L6-v2`. They are used for similarity search operations.
     */
    embedding: number[];

    /**
     * The timestamp when the document was created.
     * 
     * This field is set when the document is added to the database and provides a chronological
     * reference for document insertion.
     */
    created_at: Date;

    /**
     * A identifier for the parent document.
     *
     * */
    parentId?: string;

    isFullText: boolean;
}
