services:
  - name: my-node-app
    type: web
    runtime: node
    plan: free
    region: oregon
    buildCommand: >
      cd core && 
      pnpm install && 
      pnpm rebuild @tensorflow/tfjs-node --build-addon-from-source && 
      cd lib/base && 
      pnpm build
    startCommand: "cd core && cd agent && pnpm install && pnpm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: "23.0.0"
    autoDeploy: true