services:
  - name: my-node-app
    type: web
    runtime: node
    plan: free
    region: oregon
    buildCommand: "pnpm install && cd core && cd lib/base && pnpm build"
    startCommand: "cd agent && pnpm install && pnpm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
